version: "3.7"

services:
  database:
    image: mysql:8.0.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bot
      MYSQL_USER: botjs
      MYSQL_PASSWORD: Mattox40
    volumes:
      - ./Database:/var/lib/mysql
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    restart: always